name: Cici Viewer Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm-dev libxss1 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
            libdrm2 libxcomposite1 libxdamage1 libxrandr2 libgtk-3-0 \
            libasound2t64
          npm install

      - name: Run viewer bot
        run: node index.js
